DROP DATABASE IF EXISTS anvil;
DROP DATABASE IF EXISTS anviltest;
DROP ROLE IF EXISTS anvil;
CREATE ROLE anvil WITH LOGIN PASSWORD 'anvil';
CREATE DATABASE anvil OWNER anvil;
CREATE DATABASE anviltest OWNER anvil;

