package WWW::Anvil::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'WWW::Anvil::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=anvil',
        user => 'anvil',
        password => 'anvil',
    }
);

=head1 NAME

WWW::Anvil::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<WWW::Anvil>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<WWW::Anvil::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.4

=head1 AUTHOR

Andy Armstrong

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
